server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/
spring:
  application:
    name: GATEWAY
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin
      globalcors:
          corsConfigurations:
            '[/**]':
              allowedOrigins:
                - 'http://localhost:4200'
              allowedMethods:
                - GET
                - POST
                - PUT
                - DELETE
              allowedHeaders:
                - "*"
              allowCredentials: true

      routes:
        - id: project-service
          uri: lb://PROJECT-SERVICE
          predicates:
            - Path=/api/v1/project/**
          filters:
            - AuthenticationFilter

        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/v1/auth/**