

server:
  port: 7070



eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://3.132.56.186:8761/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5








spring:
  application:
    name: API-GATEWAY
  #  config:
  #    import: "optional:configserver:http://54.169.219.205:8088"
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - DELETE
              - PUT

      routes:
        - id: project-service
          uri: http://13.127.209.74:8060
          predicates:
            - Path=/api/v1/project/**
          filters:
            - AuthenticationFilter

        - id: auth-service
          uri: http://13.232.2.228:8070
          predicates:
            - Path=/api/v1/auth/**
        #          filters:
        #            - AuthenticationFilter

        - id: company-service
          uri: http://13.127.209.74:8010
          predicates:
            - Path=/api/v1/company/**
          filters:
            - AuthenticationFilter

        - id: admin-service
          uri: lb://ADMIN-SERVICE
          predicates:
            - Path=/api/v1/admin/**
          filters:
            - AuthenticationFilter

        - id: user-service
          uri: http://13.232.2.228:8050
          predicates:
             - Path=/api/v1/user/**
          filters:
              - AuthenticationFilter






